// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AgendaTable: typeof import('./src/components/Agenda/Table.vue')['default']
    ArrowBox: typeof import('./src/components/ArrowBox.vue')['default']
    BlockTitle: typeof import('./src/components/BlockTitle.vue')['default']
    CfpAgendaCard: typeof import('./src/components/cfp/AgendaCard.vue')['default']
    CfpAgendaType: typeof import('./src/components/cfp/AgendaType.vue')['default']
    CfpBackBtn: typeof import('./src/components/cfp/BackBtn.vue')['default']
    CfpBlockTitle: typeof import('./src/components/cfp/BlockTitle.vue')['default']
    CfpCard: typeof import('./src/components/cfp/Card.vue')['default']
    CfpCards: typeof import('./src/components/cfp/Cards.vue')['default']
    CfpCoc: typeof import('./src/components/cfp/coc.vue')['default']
    CfpDateLinks: typeof import('./src/components/cfp/DateLinks.vue')['default']
    CfpDivider: typeof import('./src/components/cfp/Divider.vue')['default']
    CfpFooter: typeof import('./src/components/cfp/Footer.vue')['default']
    CfpGlassBox: typeof import('./src/components/cfp/GlassBox.vue')['default']
    CfpPrevSite: typeof import('./src/components/cfp/PrevSite.vue')['default']
    CfpQuestionAnswer: typeof import('./src/components/cfp/QuestionAnswer.vue')['default']
    CfpQuestionBox: typeof import('./src/components/cfp/QuestionBox.vue')['default']
    CfpRadBtn: typeof import('./src/components/cfp/RadBtn.vue')['default']
    CfpRoundBtn: typeof import('./src/components/cfp/RoundBtn.vue')['default']
    CfpRoundedGlassBox: typeof import('./src/components/cfp/RoundedGlassBox.vue')['default']
    CfpSchedule: typeof import('./src/components/cfp/Schedule.vue')['default']
    CfpSessionTypeCard: typeof import('./src/components/cfp/SessionTypeCard.vue')['default']
    CfpSubmissionBtn: typeof import('./src/components/cfp/SubmissionBtn.vue')['default']
    CfpSubmissionNotice: typeof import('./src/components/cfp/SubmissionNotice.vue')['default']
    CfpSubmissionPersonalInfo: typeof import('./src/components/cfp/SubmissionPersonalInfo.vue')['default']
    CfpTimer: typeof import('./src/components/cfp/Timer.vue')['default']
    ConfettiExplosion: typeof import('./src/components/ConfettiExplosion.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GeneralHead: typeof import('./src/components/GeneralHead.vue')['default']
    LogoCatInAMaze: typeof import('./src/components/logo/CatInAMaze.vue')['default']
    LogoSitcon: typeof import('./src/components/logo/Sitcon.vue')['default']
    MintBox: typeof import('./src/components/MintBox.vue')['default']
    Modal: typeof import('./src/components/modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
